USE GVO_ADV;

CREATE TABLE IF NOT EXISTS `quest` (
    `id` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '任务id',
    `name_tc` varchar(255) NOT NULL DEFAULT '' COMMENT '任务名称（繁体）',
    `name_sc` varchar(255) NOT NULL DEFAULT '' COMMENT '任务名称（简体）',
    `type` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT '任务类型',
    `difficulty` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT '任务难度',
    `skill_1` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT '所需技能1',
    `skill_level_1` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT '所需技能1等级',
    `skill_2` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT '所需技能2',
    `skill_level_2` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT '所需技能2等级',
    `skill_3` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT '所需技能3',
    `skill_level_3` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT '所需技能3等级',
    `deposit` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '订金',
    `bonus` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '任务报酬',
    `time_limit` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '任务时限',
    `experience` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '任务经验',
    `reputation` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '任务声望',
    `discovery_id` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '关联发现物id',
    `discovery_name_tc` varchar(255) NOT NULL DEFAULT '' COMMENT '关联发现物名称（繁体）',
    `discovery_name_sc` varchar(255) NOT NULL DEFAULT '' COMMENT '关联发现物名称（简体）',
    `note` varchar(2047) NOT NULL DEFAULT '' COMMENT '任务流程',
    `item` varchar(255) NOT NULL DEFAULT '' COMMENT '获得物品',
    `city_ids` varchar(50) NOT NULL DEFAULT '' COMMENT '城市id',
    `pre_quest_ids` varchar(255) NOT NULL DEFAULT '' COMMENT '前置任务id集合',
    `after_quest_ids` varchar(255) NOT NULL DEFAULT '' COMMENT '后置任务id集合',
    `discover_area` varchar(50) NOT NULL DEFAULT 0 COMMENT '完成任务地点',
    `discover_area_x` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '完成任务地点横坐标',
    `discover_area_y` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '完成任务地点纵坐标',
    `user_comment` varchar(2047) NOT NULL DEFAULT '' COMMENT '用户评论',
    PRIMARY KEY (`id`),
    KEY `idx_discovery_id`(`discovery_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='任务表' ;
